import { Link } from 'react-router-dom';

export const Terms = () => {
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <header className="border-b border-[#E5E5E5]">
        <div className="max-w-4xl mx-auto px-8 py-8">
          <Link to="/" className="align-wordmark hover:opacity-70 transition-opacity">
            align
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-8 py-16">
        <div className="mb-12">
          <h1 className="text-[28px] font-normal text-[#1A1A18] mb-2">Terms of Service</h1>
          <p className="text-[14px] text-[#9E9E9E]">
            Last Updated: March 21, 2026 · Effective Date: March 21, 2026
          </p>
          <p className="text-[14px] text-[#9E9E9E] mt-1">
            App: Align (alignapp.world) · Contact: <a href="mailto:support@alignapp.world" className="text-[#1A1A18] underline">support@alignapp.world</a>
          </p>
        </div>

        <div className="space-y-12">
          {/* 1. Definitions */}
          <section>
            <h2 className="text-[18px] font-medium text-[#1A1A18] mb-4">1. Definitions</h2>
            <div className="space-y-3 text-[15px] text-[#6B6B6B] leading-relaxed">
              <p><strong className="text-[#1A1A18]">"Align"</strong> or <strong className="text-[#1A1A18]">"the App"</strong> refers to the Align manifestation meditation application, including all features, content, and services provided through the mobile application and website.</p>
              <p><strong className="text-[#1A1A18]">"User"</strong> or <strong className="text-[#1A1A18]">"You"</strong> refers to any individual who accesses or uses the App.</p>
              <p><strong className="text-[#1A1A18]">"Content"</strong> refers to all materials generated by or through the App, including meditation scripts, audio recordings, journal entries, and user preferences.</p>
              <p><strong className="text-[#1A1A18]">"AI Services"</strong> refers to third-party artificial intelligence services used to generate Content, specifically Anthropic Claude for text generation and ElevenLabs for voice synthesis.</p>
              <p><strong className="text-[#1A1A18]">"Personal Data"</strong> has the meaning defined in Article 4(1) of the GDPR.</p>
            </div>
          </section>

          {/* 2. Acceptance of Terms */}
          <section>
            <h2 className="text-[18px] font-medium text-[#1A1A18] mb-4">2. Acceptance of Terms</h2>
            <div className="space-y-4 text-[15px] text-[#6B6B6B] leading-relaxed">
              <p>
                By downloading, installing, accessing, or using Align, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree to these Terms, you must not use the App.
              </p>
              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">Eligibility</h3>
                <p>You must be at least 13 years of age to use Align. By using the App, you represent and warrant that you meet this age requirement. If you are under 18, you confirm that you have obtained parental or guardian consent.</p>
              </div>
              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">Changes to Terms</h3>
                <p>We reserve the right to modify these Terms at any time. Material changes will be notified via email and/or in-app notification at least 30 days before taking effect. Your continued use of the App after such changes constitutes acceptance of the modified Terms.</p>
              </div>
            </div>
          </section>

          {/* 3. Description of Service */}
          <section>
            <h2 className="text-[18px] font-medium text-[#1A1A18] mb-4">3. Description of Service</h2>
            <div className="space-y-4 text-[15px] text-[#6B6B6B] leading-relaxed">
              <p>Align is a personalized manifestation and meditation application that combines:</p>
              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">AI-Generated Content:</h3>
                <p>Personalized meditation scripts generated using Anthropic Claude based on your inputs and preferences</p>
              </div>
              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">Voice Synthesis:</h3>
                <p>Audio meditation recordings created using ElevenLabs text-to-speech technology</p>
              </div>
              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">Journaling:</h3>
                <p>Private reflection and manifestation tracking tools</p>
              </div>
              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">Progress Tracking:</h3>
                <p>Insights and analytics on your meditation practice</p>
              </div>
              <p>Align is a wellness and lifestyle application intended for personal growth and relaxation. It is not a medical device, therapeutic service, or substitute for professional mental health care.</p>
            </div>
          </section>

          {/* 4. User Accounts */}
          <section>
            <h2 className="text-[18px] font-medium text-[#1A1A18] mb-4">4. User Accounts</h2>
            <div className="space-y-4 text-[15px] text-[#6B6B6B] leading-relaxed">
              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">Account Creation</h3>
                <p>To use Align, you must create an account by providing a valid email address and creating a secure password. You may also sign up using Apple Sign-In or Google Sign-In.</p>
              </div>
              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">Account Security</h3>
                <p>You are solely responsible for:</p>
                <ul className="space-y-1 list-disc list-inside mt-2">
                  <li>Maintaining the confidentiality of your account credentials</li>
                  <li>All activities that occur under your account</li>
                  <li>Ensuring your account information is accurate and up-to-date</li>
                  <li>Notifying us immediately of any unauthorized access at <a href="mailto:support@alignapp.world" className="text-[#1A1A18] underline">support@alignapp.world</a></li>
                </ul>
              </div>
              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">Account Termination</h3>
                <p>You may delete your account at any time through the App settings or by contacting us. Upon deletion, your Personal Data will be processed in accordance with our Privacy Policy and applicable law.</p>
              </div>
            </div>
          </section>

          {/* 5. Subscriptions and Payments */}
          <section>
            <h2 className="text-[18px] font-medium text-[#1A1A18] mb-4">5. Subscriptions and Payments</h2>
            <div className="space-y-6">
              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-3">5.1 Subscription Plans</h3>
                <div className="overflow-x-auto">
                  <table className="w-full text-[14px]">
                    <thead>
                      <tr className="border-b border-[#E5E5E5]">
                        <th className="text-left py-2 text-[#1A1A18] font-medium">Tier</th>
                        <th className="text-left py-2 text-[#1A1A18] font-medium">Monthly Price</th>
                        <th className="text-left py-2 text-[#1A1A18] font-medium">Annual Price</th>
                        <th className="text-left py-2 text-[#1A1A18] font-medium">Sessions</th>
                      </tr>
                    </thead>
                    <tbody className="text-[#6B6B6B]">
                      <tr className="border-b border-[#E5E5E5]">
                        <td className="py-2">Essential</td>
                        <td className="py-2">$19.99 / month</td>
                        <td className="py-2">$149.99 / year</td>
                        <td className="py-2">3 sessions / month</td>
                      </tr>
                      <tr className="border-b border-[#E5E5E5]">
                        <td className="py-2">Pro</td>
                        <td className="py-2">$49.99 / month</td>
                        <td className="py-2">$399.99 / year</td>
                        <td className="py-2">5 sessions / month</td>
                      </tr>
                      <tr>
                        <td className="py-2">Elite</td>
                        <td className="py-2">$99.99 / month</td>
                        <td className="py-2">$799.99 / year</td>
                        <td className="py-2">10 sessions / month + downloads</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>

              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">5.2 Payment Processing</h3>
                <p className="text-[14px] text-[#6B6B6B] mb-2">All payments are processed through:</p>
                <ul className="space-y-1 text-[14px] text-[#6B6B6B] list-disc list-inside">
                  <li>iOS: Apple App Store In-App Purchase system</li>
                  <li>Android: Google Play Billing system</li>
                  <li>Web: Stripe (where applicable)</li>
                </ul>
                <p className="text-[14px] text-[#6B6B6B] mt-2">We do not store your payment card information. All payment data is handled by the respective payment processors under their terms and privacy policies.</p>
              </div>

              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">5.3 Cancellation</h3>
                <p className="text-[14px] text-[#6B6B6B]">You may cancel your subscription at any time through your Apple ID, Google Play, or Stripe account settings. Cancellation takes effect at the end of the current billing period. No refunds are issued for partial months.</p>
              </div>

              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">5.4 Price Changes</h3>
                <p className="text-[14px] text-[#6B6B6B]">We may modify subscription prices with 30 days' advance notice. Continued use after the price change constitutes acceptance.</p>
              </div>

              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">5.5 Free Trial</h3>
                <p className="text-[14px] text-[#6B6B6B]">Where offered, free trials convert to paid subscriptions unless cancelled at least 24 hours before the trial ends.</p>
              </div>
            </div>
          </section>

          {/* 6. User Content and Intellectual Property */}
          <section>
            <h2 className="text-[18px] font-medium text-[#1A1A18] mb-4">6. User Content and Intellectual Property</h2>
            <div className="space-y-4 text-[15px] text-[#6B6B6B] leading-relaxed">
              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">Your Content</h3>
                <p>You retain all ownership rights to content you create within Align, including journal entries, meditation preferences, and personal manifestation goals.</p>
              </div>
              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">License to Us</h3>
                <p>By using Align, you grant us a limited, non-exclusive, royalty-free license to:</p>
                <ul className="space-y-1 list-disc list-inside mt-2">
                  <li>Process your inputs to generate personalized meditations</li>
                  <li>Store your Content securely</li>
                  <li>Display your Content to you within the App</li>
                  <li>Use anonymized data to improve our AI models (as described in the Privacy Policy)</li>
                </ul>
              </div>
              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">AI-Generated Content</h3>
                <p>Meditation scripts and audio generated by our AI Services are created specifically for you based on your inputs. While you have a personal license to use this Content, you may not resell, redistribute, or commercially exploit AI-generated meditations, use them to create competing products, or remove any attribution.</p>
              </div>
            </div>
          </section>

          {/* 7. Acceptable Use Policy */}
          <section>
            <h2 className="text-[18px] font-medium text-[#1A1A18] mb-4">7. Acceptable Use Policy</h2>
            <p className="text-[15px] text-[#6B6B6B] mb-4">You agree not to:</p>
            <ul className="space-y-2 text-[14px] text-[#6B6B6B] list-disc list-inside">
              <li>Use Align for any unlawful purpose or in violation of any applicable law</li>
              <li>Attempt to gain unauthorized access to the App, its systems, or other users' accounts</li>
              <li>Interfere with or disrupt the App's functionality, servers, or networks</li>
              <li>Use automated means (bots, scrapers) to access the App without written permission</li>
              <li>Upload or transmit viruses, malware, or harmful code</li>
              <li>Harass, abuse, or harm other users</li>
              <li>Impersonate any person or entity</li>
              <li>Use Align to generate content that is illegal, harmful, threatening, abusive, defamatory, or discriminatory</li>
              <li>Reverse engineer, decompile, or disassemble any part of the App</li>
              <li>Circumvent any security or access controls</li>
            </ul>
            <p className="text-[14px] text-[#6B6B6B] mt-4">Violation of this policy may result in immediate account suspension or termination, and potential legal action.</p>
          </section>

          {/* 8. AI-Generated Content Disclaimer */}
          <section>
            <h2 className="text-[18px] font-medium text-[#1A1A18] mb-4">8. AI-Generated Content Disclaimer</h2>
            <div className="space-y-4 text-[15px] text-[#6B6B6B] leading-relaxed">
              <p>Meditation scripts and audio are generated by artificial intelligence (Anthropic Claude and ElevenLabs) based on your inputs. While we strive for quality and relevance:</p>
              <ul className="space-y-2 list-disc list-inside">
                <li>AI-generated content may not always be accurate, appropriate, or suitable for your specific needs</li>
                <li>The App does not provide medical, psychological, or therapeutic advice</li>
                <li>AI-generated meditations are for general wellness and personal growth purposes only</li>
              </ul>
              <p>Align is not a substitute for professional medical care, mental health treatment, or therapy. If you are experiencing mental health difficulties, please consult a qualified healthcare professional.</p>
            </div>
          </section>

          {/* 9. Third-Party Services */}
          <section>
            <h2 className="text-[18px] font-medium text-[#1A1A18] mb-4">9. Third-Party Services</h2>
            <p className="text-[15px] text-[#6B6B6B] mb-4">Align integrates with the following third-party services:</p>
            <ul className="space-y-3 text-[14px] text-[#6B6B6B]">
              <li><strong className="text-[#1A1A18]">Anthropic Claude</strong> — Used for generating meditation scripts. Subject to Anthropic's Terms & Privacy Policy.</li>
              <li><strong className="text-[#1A1A18]">ElevenLabs</strong> — Used for text-to-speech voice synthesis. Subject to ElevenLabs' Terms & Privacy Policy.</li>
              <li><strong className="text-[#1A1A18]">RevenueCat</strong> — Used for subscription management. Subject to RevenueCat's Privacy Policy.</li>
              <li><strong className="text-[#1A1A18]">Apple App Store / Google Play</strong> — Used for app distribution and payment processing. Subject to their respective terms.</li>
            </ul>
            <p className="text-[14px] text-[#6B6B6B] mt-4">We are not responsible for the practices of these third parties. Your use of their services is governed by their terms.</p>
          </section>

          {/* 10. Disclaimers and Warranties */}
          <section>
            <h2 className="text-[18px] font-medium text-[#1A1A18] mb-4">10. Disclaimers and Warranties</h2>
            <p className="text-[15px] text-[#6B6B6B] leading-relaxed">
              The App is provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind, either express or implied. To the fullest extent permitted by law, we disclaim all warranties including merchantability, fitness for a particular purpose, non-infringement, accuracy of AI-generated content, and uninterrupted or error-free service.
            </p>
            <p className="text-[15px] text-[#6B6B6B] leading-relaxed mt-4">
              We do not guarantee that using Align will result in any specific outcome, manifestation, or personal achievement.
            </p>
          </section>

          {/* 11. Limitation of Liability */}
          <section>
            <h2 className="text-[18px] font-medium text-[#1A1A18] mb-4">11. Limitation of Liability</h2>
            <p className="text-[15px] text-[#6B6B6B] leading-relaxed mb-4">
              To the maximum extent permitted by applicable law, we shall not be liable for indirect, incidental, special, consequential, or punitive damages, loss of profits, revenue, data, or goodwill, personal injury or emotional distress, damages arising from AI-generated content, or service interruptions or data loss.
            </p>
            <p className="text-[15px] text-[#6B6B6B] leading-relaxed">
              Our total liability to you for any claim shall not exceed the amount you paid to us in the 12 months preceding the claim, or €100, whichever is greater.
            </p>
            <p className="text-[15px] text-[#6B6B6B] leading-relaxed mt-4">
              Nothing in these Terms excludes liability for death or personal injury caused by negligence, fraud, or any liability that cannot be excluded by applicable law.
            </p>
          </section>

          {/* 12. Indemnification */}
          <section>
            <h2 className="text-[18px] font-medium text-[#1A1A18] mb-4">12. Indemnification</h2>
            <p className="text-[15px] text-[#6B6B6B] leading-relaxed">
              You agree to indemnify and hold harmless Align, its officers, directors, employees, and agents from any claims, damages, losses, liabilities, costs, or expenses (including reasonable attorneys' fees) arising from your use of the App, your violation of these Terms, your violation of any third-party rights, or your conduct in connection with the App.
            </p>
          </section>

          {/* 13. Governing Law and Dispute Resolution */}
          <section>
            <h2 className="text-[18px] font-medium text-[#1A1A18] mb-4">13. Governing Law and Dispute Resolution</h2>
            <div className="space-y-4 text-[15px] text-[#6B6B6B] leading-relaxed">
              <p>These Terms shall be governed by the laws of the Netherlands. Any dispute shall be subject to the exclusive jurisdiction of the courts of Rotterdam, Netherlands.</p>
              <p>Before filing a claim, you agree to attempt to resolve disputes informally by contacting us at <a href="mailto:support@alignapp.world" className="text-[#1A1A18] underline">support@alignapp.world</a>. We will attempt to resolve the dispute within 30 days.</p>
              <p>You agree that any proceedings will be conducted only on an individual basis and not in a class, consolidated, or representative action.</p>
            </div>
          </section>

          {/* 14. Termination */}
          <section>
            <h2 className="text-[18px] font-medium text-[#1A1A18] mb-4">14. Termination</h2>
            <div className="space-y-4 text-[15px] text-[#6B6B6B] leading-relaxed">
              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">By Us</h3>
                <p>We may suspend or terminate your account immediately if you violate these Terms, engage in fraudulent activity, pose a security risk, or fail to pay subscription fees.</p>
              </div>
              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">By You</h3>
                <p>You may terminate your account at any time by deleting the App or contacting us.</p>
              </div>
              <div>
                <h3 className="text-[15px] font-medium text-[#1A1A18] mb-2">Effect of Termination</h3>
                <p>Upon termination, your right to use the App ceases immediately. Your Content will be deleted in accordance with our data retention policy. Any outstanding subscription fees remain due.</p>
              </div>
            </div>
          </section>

          {/* 15. General Provisions */}
          <section>
            <h2 className="text-[18px] font-medium text-[#1A1A18] mb-4">15. General Provisions</h2>
            <div className="space-y-3 text-[15px] text-[#6B6B6B] leading-relaxed">
              <p><strong className="text-[#1A1A18]">Severability:</strong> If any provision is found unenforceable, the remaining provisions remain in full effect.</p>
              <p><strong className="text-[#1A1A18]">Waiver:</strong> Our failure to enforce any right does not constitute a waiver of such right.</p>
              <p><strong className="text-[#1A1A18]">Assignment:</strong> You may not assign these Terms without our written consent. We may assign them without restriction.</p>
              <p><strong className="text-[#1A1A18]">Force Majeure:</strong> We are not liable for failures caused by circumstances beyond our reasonable control.</p>
              <p><strong className="text-[#1A1A18]">Entire Agreement:</strong> These Terms constitute the entire agreement between you and us regarding the App.</p>
            </div>
          </section>

          {/* 16. Contact */}
          <section>
            <h2 className="text-[18px] font-medium text-[#1A1A18] mb-4">16. Contact</h2>
            <div className="space-y-2 text-[14px] text-[#6B6B6B]">
              <p>Email: <a href="mailto:support@alignapp.world" className="text-[#1A1A18] underline">support@alignapp.world</a></p>
              <p>Response time: Within 48 hours</p>
              <p>Website: <a href="https://alignapp.world" className="text-[#1A1A18] underline">alignapp.world</a></p>
            </div>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-[#E5E5E5] mt-16">
        <div className="max-w-4xl mx-auto px-8 py-8">
          <div className="flex justify-between items-center">
            <Link to="/" className="align-wordmark hover:opacity-70 transition-opacity">
              align
            </Link>
            <div className="flex gap-6">
              <Link to="/privacy-policy" className="micro-label hover:text-[#1A1A18] transition-colors">Privacy</Link>
              <Link to="/terms" className="micro-label hover:text-[#1A1A18] transition-colors">Terms</Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Terms;
